dist: wheezy
sudo: on
addons:
  apt:
    packages:
      - python-dev

install: 
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | tee /etc/apt/sources.list.d/azure-cli.list
  - apt-key adv --keyserver packages.microsoft.com --recv-keys 417A0893
  - apt-get install apt-transport-https
  - apt-get update && sudo apt-get install azure-cli
  - apt-get install snapd
  - snap install hugo

cache: 
  - az
  - hugo

# Build the website
script:
  - hugo
  - python deploy.py
